name: .NET Core CI 

on:
  push:
    branches:
      - develop
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore SoftUnibazar.sln

      - name: Build
        run: dotnet build SoftUnibazar.sln --configuration Release --no-restore

      - name: Tests
        run: dotnet test SoftUnibazar.IntegrationTests/SoftUnibazar.IntegrationTests.csproj
